name: 'Setup Gradle & Java Action'
description: 'Setup Gradle & Java for the project'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  jdk-version:
    description: 'Version of JVM to setup'
    required: true

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4
    - uses: gradle/wrapper-validation-action@v2

    - name: Use JDK ${{ inputs.jdk-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.jdk-version }}
        distribution: 'temurin'
        cache: 'gradle'

    - name: Make Gradle Wrapper Executable
      shell: bash
      run: chmod +x ./gradlew

    - name: Setup Gradle Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

    - name: Build Project
      shell: bash
      run: |
        if [ "${{ steps.cache.outputs.cache-hit }}" != "true" ]; then
          ./gradlew build
        fi